// <auto-generated />
using System;
using InspecaoVeicularPetroeng.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InspecaoVeicularPetroeng.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309171941_classes_principais")]
    partial class classes_principais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Evidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("evidencias", (string)null);
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Foto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EvidenciaId")
                        .HasColumnType("integer");

                    b.Property<string>("Extensao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("VistoriaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EvidenciaId");

                    b.HasIndex("VistoriaId");

                    b.ToTable("fotos", (string)null);
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Inspecao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<long>("VistoriaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("VistoriaId");

                    b.ToTable("inspecoes", (string)null);
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("itens", (string)null);
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.StatusVistoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("status_vistoria", (string)null);
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_completo");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("perfil");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("senha");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("p_k_usuarios");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("veiculos", (string)null);
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Vistoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int>("QuilometragemVeiculo")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("vistorias", (string)null);
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Foto", b =>
                {
                    b.HasOne("InspecaoVeicularPetroeng.Domain.Entities.Evidencia", "Evidencia")
                        .WithMany("Fotos")
                        .HasForeignKey("EvidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InspecaoVeicularPetroeng.Domain.Entities.Vistoria", "Vistoria")
                        .WithMany("Fotos")
                        .HasForeignKey("VistoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evidencia");

                    b.Navigation("Vistoria");
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Inspecao", b =>
                {
                    b.HasOne("InspecaoVeicularPetroeng.Domain.Entities.Item", "Item")
                        .WithMany("Inspecoes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InspecaoVeicularPetroeng.Domain.Entities.Vistoria", "Vistoria")
                        .WithMany("Inspecoes")
                        .HasForeignKey("VistoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Vistoria");
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Vistoria", b =>
                {
                    b.HasOne("InspecaoVeicularPetroeng.Domain.Entities.StatusVistoria", "Status")
                        .WithMany("Vistorias")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InspecaoVeicularPetroeng.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany("Vistorias")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Evidencia", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Item", b =>
                {
                    b.Navigation("Inspecoes");
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.StatusVistoria", b =>
                {
                    b.Navigation("Vistorias");
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Veiculo", b =>
                {
                    b.Navigation("Vistorias");
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Vistoria", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("Inspecoes");
                });
#pragma warning restore 612, 618
        }
    }
}
