// <auto-generated />
using System;
using InspecaoVeicularPetroeng.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InspecaoVeicularPetroeng.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320193927_projeto_iniciado")]
    partial class projeto_iniciado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("p_k_contratos");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("contratos", (string)null);
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Evidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("p_k_evidencias");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("evidencias", (string)null);
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Foto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("EvidenciaId")
                        .HasColumnType("integer")
                        .HasColumnName("evidencia_id");

                    b.Property<string>("Extensao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("extensao");

                    b.Property<long>("VistoriaId")
                        .HasColumnType("bigint")
                        .HasColumnName("vistoria_id");

                    b.HasKey("Id")
                        .HasName("p_k_fotos");

                    b.HasIndex("EvidenciaId")
                        .HasDatabaseName("i_x_fotos_evidencia_id");

                    b.HasIndex("VistoriaId")
                        .HasDatabaseName("i_x_fotos_vistoria_id");

                    b.ToTable("fotos", (string)null);
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Inspecao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<long>("VistoriaId")
                        .HasColumnType("bigint")
                        .HasColumnName("vistoria_id");

                    b.HasKey("Id")
                        .HasName("p_k_inspecoes");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("i_x_inspecoes_item_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("i_x_inspecoes_status_id");

                    b.HasIndex("VistoriaId")
                        .HasDatabaseName("i_x_inspecoes_vistoria_id");

                    b.ToTable("inspecoes", (string)null);
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("p_k_itens");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("itens", (string)null);
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.StatusInspecao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("p_k_status_inspecao");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("status_inspecao", (string)null);
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ContratoId")
                        .HasColumnType("integer")
                        .HasColumnName("contrato_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_completo");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("perfil");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("senha");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("p_k_usuarios");

                    b.HasIndex("ContratoId")
                        .HasDatabaseName("i_x_usuarios_contrato_id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<int>("ContratoId")
                        .HasColumnType("integer")
                        .HasColumnName("contrato_id");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("placa");

                    b.HasKey("Id")
                        .HasName("p_k_veiculos");

                    b.HasIndex("ContratoId")
                        .HasDatabaseName("i_x_veiculos_contrato_id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("veiculos", (string)null);
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Vistoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<double>("QuilometragemVeiculo")
                        .HasColumnType("double precision")
                        .HasColumnName("quilometragem_veiculo");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id")
                        .HasName("p_k_vistorias");

                    b.HasIndex("VeiculoId")
                        .HasDatabaseName("i_x_vistorias_veiculo_id");

                    b.ToTable("vistorias", (string)null);
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Foto", b =>
                {
                    b.HasOne("InspecaoVeicularPetroeng.Domain.Entities.Evidencia", "Evidencia")
                        .WithMany("Fotos")
                        .HasForeignKey("EvidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InspecaoVeicularPetroeng.Domain.Entities.Vistoria", "Vistoria")
                        .WithMany("Fotos")
                        .HasForeignKey("VistoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evidencia");

                    b.Navigation("Vistoria");
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Inspecao", b =>
                {
                    b.HasOne("InspecaoVeicularPetroeng.Domain.Entities.Item", "Item")
                        .WithMany("Inspecoes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InspecaoVeicularPetroeng.Domain.Entities.StatusInspecao", "Status")
                        .WithMany("Inspecoes")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InspecaoVeicularPetroeng.Domain.Entities.Vistoria", "Vistoria")
                        .WithMany("Inspecoes")
                        .HasForeignKey("VistoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Status");

                    b.Navigation("Vistoria");
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("InspecaoVeicularPetroeng.Domain.Entities.Contrato", "Contrato")
                        .WithMany("Usuarios")
                        .HasForeignKey("ContratoId");

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Veiculo", b =>
                {
                    b.HasOne("InspecaoVeicularPetroeng.Domain.Entities.Contrato", "Contrato")
                        .WithMany("Veiculos")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Vistoria", b =>
                {
                    b.HasOne("InspecaoVeicularPetroeng.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany("Vistorias")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Contrato", b =>
                {
                    b.Navigation("Usuarios");

                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Evidencia", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Item", b =>
                {
                    b.Navigation("Inspecoes");
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.StatusInspecao", b =>
                {
                    b.Navigation("Inspecoes");
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Veiculo", b =>
                {
                    b.Navigation("Vistorias");
                });

            modelBuilder.Entity("InspecaoVeicularPetroeng.Domain.Entities.Vistoria", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("Inspecoes");
                });
#pragma warning restore 612, 618
        }
    }
}
